# Користувачі для тестування (паролі у відкритому вигляді, що є НЕБЕЗПЕЧНО для продакшену!)
# формат: логін=пароль,роль1,роль2,...

# Користувач з роллю USER
user=pass,USER

# Користувач з роллю ADMIN
admin=admin,ADMIN

